### ISSUE TITLE
Current state of the project

### ISSUE THREAD

**Issue by rchastain** [pascaldragon/kwirk#1]
Hello!

I wonder what is the current state of that project. I could compile and run it (with two little modifications) on Linux, but I have not yet found how to use it. For now, it crashes because of a file not found.

I spent many time, last days, trying to port to ptcGraph old Turbo Pascal games (with more or less success). That's why I am interested in that project. If ever you feel motivated to work again on it, I would be glad to help.

I see in your commits history that you converted some pictures to ptcGraph format. I would be interested to know how you did, because I tried to do the same with another game, and I didn't succeed. I attach the source of that game here, in case you would want to take a look.

Regards.

Roland

[geotz-pacman.zip](https://github.com/pascaldragon/kwirk/files/6419498/geotz-pacman.zip)

**Comment by pascaldragon** [comment]
Hello Roland,

In principle it's working though I haven't worked on it in a long time to my embarrasment. 😣

I assume the fixes you mean are:
- commenting the `KwirkReadKey` in `JME_Demo` or adding the unit `CrtUtils`
- adding unit `cthreads` for Unix-like systems

(I've applied those fixes now as well)

Aside from that you need to make sure that the `kwirk` binary, the `ptcimages.img` and also the font files (I simply took them from a Turbo Pascal installation, e.g. `GOTH.CHR`; I dount know how “redistributable” they are). The `maz` files _can_ be there as well though you specify the level through a parameter (the in-game selector is not working yet).

Please note that for some reason you should use FPC 3.0.4 if you want to enjoy the graphics correctly, cause it seems that 3.2.0 changed/broke something there... 😕 Also something is still off with the sizing if the window size is large (the game field will be in the upper left and all the text far to the right).
If you start with `-text` or `/text` you can run it in text mode (though the encoding will be wrong and thus the characters won't look nice), however I've only tested that on Windows and not Linux.

Regarding your other question: The image format of the graphic system consists of a header followed by the image data _in the format the graph driver expects_.

The header looks like this:
- Width (Int16 in TP, Int32 in FPC)
- Height (Int16 in TP, Int32 in FPC)
- Reserved (Int16 in TP, Int32 in FPC)

In your case it looks like the image format is 16 colors, so it's 4-bit per Pixel. For PTC it can be either 8-, 16- or 32-bit depending on what mode is selected (this might also be the reason why FPC 3.2.0 has a wrong result here compared to 3.0.4 as something might have changed there). Back then I had written a simple tool that converts the images provided with Kwirk to those understood by FPC (it read the images, converted the colors accordingly and then wrote them using fcl-image as ordinary bitmaps; I used another, similar tool to generate a suitable _img_ file for PTC then).

I hope this helps you.

With kind regards,
PascalDragon

**Comment by pascaldragon** [comment]
Okay, I've fixed the issue with 3.2.0 (from 3.2.0 on PTCGraph supports 32-bit modes, thus that needed to be handled correctly) and I've now tested the text mode on Linux as well (had to disable some debug output).
One remaining issue seems to be that using the fonts from TP leads to to an exception on Linux, but not on Windows... will have to find out what _that_ is now... 🤔

**Comment by rchastain** [comment]
Thank you for your answer. I will study these informations, and come back to the discussion.

**Comment by rchastain** [comment]
Thank you for your latest commits. I could compile and run the game. I did put the _kwirk_ binary in the root directory, with a copy of _kwirk16.img_, and run it like this: `./kwirk mazes/goingup1.maz`.

I didn't really understand how to use TP fonts, but since you say it doesn't work on Linux... (By the way, I didn't even know that it was possible to use TP fonts with ptcGraph.)

I have not yet tested the text mode.

Thank you for the informations about ptcGraph image format. I will try again to convert the Pacman pictures.

Maybe you could convert _readme.txt_ to utf-8, for a better display on GitHub? Just in case, I attach the file here.

I close the issue.

Regards.

Roland

[readme-utf8.zip](https://github.com/pascaldragon/kwirk/files/6445337/readme-utf8.zip)

**Comment by pascaldragon** [comment]
The TP fonts are handled by the platform independent part of the Graph system (though specific implementations can hook into it to optimize it), ,hus in general they work on any platform that supports the Graph system.

Thank you for the converted _readme.txt_, I've applied it. 😊 Though there still seem to be some characters that are wrong... 🤔

**Comment by rchastain** [comment]
> Though there still seem to be some characters that are wrong...

Indeed. For your information, I converted the file like this:

```
[roland@localhost kwirk (master)]$ mv readme.txt readme.bak
[roland@localhost kwirk (master)]$ iconv -f ibm850 -t utf-8 readme.bak > readme.txt
[roland@localhost kwirk (master)]$ 
```

Maybe we should use another "from" encoding.

Encoding identification tools give weird results with the original file:

```
[roland@localhost kwirk (master)]$ uchardet readme.txt
EUC-JP
[roland@localhost kwirk (master)]$ file -i readme.txt
readme.txt: application/octet-stream; charset=binary
```

**Comment by rchastain** [comment]
Using cp437 it looks better.

[readme-utf8-2.zip](https://github.com/pascaldragon/kwirk/files/6445992/readme-utf8-2.zip)

**Comment by pascaldragon** [comment]
You're right! CP437 looks better. Thank you again! 😊 (that will probably also come in handy when I adjust the text mode)

**Comment by rchastain** [comment]
You are welcome. See you soon!
